language: go
go:
  - 1.8
  - 1.9
  - master
install: true
script:
- go build -v
- go test -v -cover ./cwl
deploy:
  provider: releases
  api_key:
    secure: B2is4VWiVzGdqHB2jK/nOjtliatenYMgoubVG4X6hnhVCbJ2rUzWOuDbImHTIJ3BbSeEGv35iwe9LTsit9cfJ5wE4P/s4B5+Ce65FivZ6Nby/RuLNlQsKNjzCEquZTcqFgMYBBxUABjgRcNHpEkYT1ZZnfoS9JPxHk2qrvyVVlOcOlW+h4ujh/eafhZkoaOguglxcXcsqU+SXr9KlpY11SkZVpDB1Mxrsaxod2WcefPKN/oiBuB1DlYjy64wYSl0zh4xFwaVxgFUoMBxFq60iEFeH3PEu6eEh6PWWgFkbHmh9D5EoBivkFHrVMXcsIyz5ZeqP3VbzulUO9PPr54fQcZ1ghJQkXC9BQCiDlxCDjiahRkicwpUCIj2q0zJiiDQzhReJSWCjfCOdgVixo/ZRhAoQCE+u0j6KtbIM3A3ssaa+74q3Q1DWp1w2PlUbW7bzmt/hNnkZ/OIjaNzBGOLfFwTUbKQ30iQujp8u6jzbR62ZVtAL0dN4i2YYihKrlYX3dpZXUeaL3Pwpr55H7FMjCtR56VgLHE7nqRqLdYauONwlWHEp7Ig9T/4dnCMd+XyLDJPY7SREhTJhBGEYSgoRqr8C5BZ1q5Owq3NavObiacXOnd9/WsgyQpsOK6/vd8ANzJmDuP1DE6UFIq/2E1MGL3Y2rbsknQ+68xgmo2b5x0=
  file: cloudwatchlogsbeat
  skip_cleanup: true
  on:
    tags: true
    branch: master
    go: 1.9
